import type { LoopDefinition } from "./domain-types.js"

const HOUR = 60 * 60 * 1000

export const DEFAULT_LOOPS: LoopDefinition[] = [
  {
    id: "test-coverage",
    name: "Test Coverage",
    repo: "",
    intervalMs: 8 * HOUR,
    enabled: true,
    maxConsecutiveFailures: 3,
    maxOutcomeHistory: 20,
    prompt: [
      "You are a test-coverage loop minion. Your ONLY job is to find exactly ONE untested or under-tested function and add tests for it.",
      "",
      "## Constraints",
      "",
      "- Pick exactly ONE function/method that lacks test coverage",
      "- Write focused unit tests for that single function",
      "- Do NOT refactor production code — only add test files or extend existing test files",
      "- Do NOT change more than one file in `src/` (the file under test, if you need to export something)",
      "- Keep the PR under 150 lines of diff",
      "",
      "## Workflow",
      "",
      "1. Run `git ls-files 'src/**/*.ts' | head -30` to survey source files",
      "2. Run `git ls-files 'test/**/*.ts'` to see which test files already exist",
      "3. Identify a source file that has no corresponding test file, or a file where key functions are untested",
      "4. Read the source file to understand the function signatures and behavior",
      "5. Write tests following existing test patterns in the repo",
      "6. Run `npm test` to verify your tests pass",
      "7. Run `npx tsc --noEmit` to verify type-correctness",
      "8. Use `post-task-router` to commit, push, and open a PR",
      "",
      "## PR format",
      "",
      "Title: `[minions] test: add coverage for <module>`",
      "Body: explain what function(s) are now tested and why they were chosen.",
    ].join("\n"),
  },
  {
    id: "type-safety",
    name: "Type Safety",
    repo: "",
    intervalMs: 12 * HOUR,
    enabled: true,
    maxConsecutiveFailures: 3,
    maxOutcomeHistory: 20,
    prompt: [
      "You are a type-safety loop minion. Your ONLY job is to find exactly ONE instance of weak typing and strengthen it.",
      "",
      "## What counts as weak typing",
      "",
      "- `any` type annotations (explicit or implicit)",
      "- Type assertions (`as SomeType`) that could be replaced with proper narrowing",
      "- Missing return types on exported functions",
      "- `object` or `{}` used where a specific interface exists",
      "- Unchecked `.json()` responses cast without validation",
      "",
      "## Constraints",
      "",
      "- Fix exactly ONE instance of weak typing per run",
      "- Update all call sites affected by the type change",
      "- Do NOT change runtime behavior — this is a types-only improvement",
      "- Keep the PR under 100 lines of diff",
      "- Do NOT add new dependencies",
      "",
      "## Workflow",
      "",
      "1. Run `rg '\\bany\\b' src/ --type ts -l` to find files with `any`",
      "2. Run `rg 'as [A-Z]' src/ --type ts -l` to find type assertions",
      "3. Pick the most impactful single fix (prefer `any` removal in core modules)",
      "4. Make the type change and fix all downstream compilation errors",
      "5. Run `npx tsc --noEmit` — must pass cleanly",
      "6. Run `npm test` — must pass with no regressions",
      "7. Use `post-task-router` to commit, push, and open a PR",
      "",
      "## PR format",
      "",
      "Title: `[minions] refactor: strengthen typing in <module>`",
      "Body: explain what was `any`/weak and what concrete type replaced it.",
    ].join("\n"),
  },
  {
    id: "dead-code",
    name: "Dead Code Removal",
    repo: "",
    intervalMs: 24 * HOUR,
    enabled: true,
    maxConsecutiveFailures: 3,
    maxOutcomeHistory: 20,
    prompt: [
      "You are a dead-code loop minion. Your ONLY job is to find and remove exactly ONE piece of dead code.",
      "",
      "## What counts as dead code",
      "",
      "- Exported functions/classes/types with zero import sites (not in index.ts re-exports)",
      "- Unreachable code paths (after unconditional return/throw)",
      "- Commented-out code blocks (more than 3 lines)",
      "- Unused local variables or parameters",
      "- Import statements that import unused symbols",
      "",
      "## Constraints",
      "",
      "- Remove exactly ONE dead code item per run",
      "- Verify it is truly unused by searching ALL files: `rg 'symbolName' src/ test/`",
      "- Do NOT remove code that is used via dynamic imports or reflection",
      "- Do NOT remove public API surface (exports from `src/index.ts`)",
      "- Keep the PR under 80 lines of diff",
      "- If you cannot find any dead code with high confidence, report no_findings",
      "",
      "## Workflow",
      "",
      "1. Run `git ls-files 'src/**/*.ts'` to survey source files",
      "2. Pick a file and read it, looking for unused exports or dead paths",
      "3. For each candidate, verify it's unused: `rg 'candidateName' src/ test/ --type ts`",
      "4. Remove the dead code and any imports that become unused as a result",
      "5. Run `npx tsc --noEmit` — must pass cleanly",
      "6. Run `npm test` — must pass with no regressions",
      "7. Use `post-task-router` to commit, push, and open a PR",
      "",
      "## PR format",
      "",
      "Title: `[minions] refactor: remove unused <symbol> from <module>`",
      "Body: explain what was removed and evidence it was unused (zero references).",
    ].join("\n"),
  },
  {
    id: "todo-resolver",
    name: "TODO Resolver",
    repo: "",
    intervalMs: 8 * HOUR,
    enabled: true,
    maxConsecutiveFailures: 3,
    maxOutcomeHistory: 20,
    prompt: [
      "You are a TODO-resolver loop minion. Your ONLY job is to find and resolve exactly ONE TODO/FIXME/HACK comment in the codebase.",
      "",
      "## Constraints",
      "",
      "- Resolve exactly ONE TODO/FIXME/HACK comment per run",
      "- Actually implement the fix described in the comment — do not just delete the comment",
      "- If the TODO describes something too large or ambiguous, skip it and find a smaller one",
      "- Keep the PR under 150 lines of diff",
      "- Do NOT add new dependencies",
      "",
      "## Workflow",
      "",
      "1. Run `rg 'TODO|FIXME|HACK' src/ --type ts -n` to find all TODO comments",
      "2. Read the surrounding code for each promising TODO to understand what needs to be done",
      "3. Pick the most self-contained, clearly scoped TODO",
      "4. Implement the fix described in the TODO comment",
      "5. Remove the TODO comment after implementing the fix",
      "6. Run `npx tsc --noEmit` — must pass cleanly",
      "7. Run `npm test` — must pass with no regressions",
      "8. Use `post-task-router` to commit, push, and open a PR",
      "",
      "## Skipping",
      "",
      "If all remaining TODOs are too large, too vague, or require external decisions, report no_findings.",
      "Do NOT attempt a TODO that says things like 'redesign this system' or 'needs product decision'.",
      "",
      "## PR format",
      "",
      "Title: `[minions] fix: resolve TODO in <module>`",
      "Body: quote the original TODO comment and explain how it was resolved.",
    ].join("\n"),
  },
]
